# Generated by Django 3.1 on 2020-09-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_customermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='phonemo',
            new_name='phoneno',
        ),
    ]
