# Generated by Django 3.1 on 2020-09-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_ordermodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='phoneno',
        ),
    ]
