# Generated by Django 3.1 on 2020-09-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0006_remove_ordermodel_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='phoneno',
            new_name='Mobile_No',
        ),
    ]
